language: node_js
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
node_js:
  - "stable"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install typescript && npm install
  - npm run build